# Be sure to restart your server when you modify this file.
# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Environmental secrets are only available for that specific environment.
default: &default
  # Your secret key is used for verifying the integrity of signed cookies.
  # If you change this key, all old signed cookies will become invalid!

  # Make sure the secret is at least 30 characters and all random,
  # no regular words or you'll be exposed to dictionary attacks.
  # You can use `rails secret` to generate a secure secret key.
  secret_key_base: "<%%= ENV['RAILS_SECRET_KEY_BASE'] %>"

development:
  <<: *default

test:
  <<: *default

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.
production:
  <<: *default


